### PR TITLE
Make compatible to Lingo 2.0; introduce extension.json

### PR DESCRIPTION
**Pull request by s7eph4n**

### CODE REVIEW

**Comment by s7eph4n** [comment]
@mwjames Could you give this a spin?
After `composer update` you'll need to `git pull` both Lingo and SG to make sure they are on their latest dev version.
You'll also need to add `wfLoadExtension('SemanticGlossary');` to LocalSettings.php.

**Comment by mwjames** [comment]
> Could you give this a spin?

I gave it a local spin and when running `composer phpunit` I needed to ensure (bootstrap)  and also isolate the access to the `ExtensionRegistry` class hence:

```
if ( ( $version = SemanticGlossary::getVersion() ) === null ) {
	die( 'SemanticGlossary is not registered via wfLoadExtension, please adapt your LocalSettings.' );
}
```

```
	/**
	 * @since 2.0
	 *
	 * @return string|null
	 */
	public static function getVersion() {
		$extensionData = ExtensionRegistry::getInstance()->getAllThings();

		if ( isset( $extensionData['Semantic Glossary'] ) ) {
			return $extensionData['Semantic Glossary']['version'];
		}

		return null;
	}
```

As soon as I added `wfLoadExtension` to LocalSetting I encountered https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1424, so I'm a bit hang up on solving this issue.

> After composer update you'll need to git pull both Lingo and SG to make sure they are on their latest dev version.

Should happen according to https://github.com/SemanticMediaWiki/SemanticGlossary/blob/master/tests/travis/install-semantic-glossary.sh#L34-L41

One thing that doesn't match up is the Lingo packagist @dev reference which has on old hash 8b90293ff pointing to `\Extension\Lingo`.

Since Lingo isn't released yet, composer.josn should probably point to @dev for the time being.

**Comment by s7eph4n** [comment]
Thanks @mwjames !
I'll encapsulate the call to the singleton.
Regarding the dependency I think I'll just release Lingo 2.0. I intend to improve it's test coverage, but if I waited with the release until I had something substantial, it would probably take between a while and forever.

**Comment by s7eph4n** [comment]
I'll have to push this to get the test running. The tests gets the SG 1.x composer.json from packagist and installs Lingo 1.x. Git pull is not changing that.

**Pull request merged**
