### PR TITLE
Avoid static methods when registering Properties

### PR DESCRIPTION
**Pull request by s7eph4n**
This PR is made in reference to: #33, #35

This PR addresses or contains:
- Replace calls of static methods by calls to injected params
- Rename PropertyRegistry -> PropertyRegistrationHelper
- Update PropertyRegistrationHelperTest

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@s7eph4n Got:

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Lingo is not compatible with the current MediaWiki core (version 1.26.4), it requires: ~1.27.' in /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php:206
Stack trace:
#0 /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php(127): ExtensionRegistry->readFromQueue(Array)
#1 /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php(294): ExtensionRegistry->loadFromQueue()
#2 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticGlossary/SemanticGlossary.php(27): ExtensionRegistry->load('/home/travis/bu...')
#3 [internal function]: SemanticGlossary::initExtension()
#4 /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php(269): call_user_func('SemanticGlossar...')
#5 /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php(128): ExtensionRegistry->exportExtractedData(Array)
#6 /home/travis/build/SemanticMediaWiki/mw/includ in /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php on line 206
Fatal error: Uncaught exception 'Exception' with message 'Lingo is not compatible with the current MediaWiki core (version 1.26.4), it requires: ~1.27.' in /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php on line 206
```

**Comment by s7eph4n** [comment]
Yeah, just saw it. Not sure what to do.

**Comment by mwjames** [comment]
> Yeah, just saw it. Not sure what to do.

Well, the test calls for MW 1.26.4 and Lingo/ExtensionRegistry says it needs 1.27+.

**Comment by s7eph4n** [comment]
Yes. So I could either change Lingo to support 1.26 again or require MW 1.27 for SG.

**Comment by mwjames** [comment]
> Lingo to support 1.26 again or require MW 1.27 for SG.

1.26 is a dead horse, I'd say 1.27 as min.

**Comment by s7eph4n** [comment]
Ok, let's do that. Just had a look: Last 1.26 release was 1.5 years ago.

**Pull request merged**
