### PR TITLE
Make 4.0 release

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #54 

This PR addresses or contains:
- Updated README
- Added notes about the release
- Bumps version
- Tidies and updates 

This PR includes:
- [x] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes: #54

### CODE REVIEW

**Comment by kghbln** [comment]
@hexmode @krabina As promised the pull for the next release, field tested for MW 1.35

**Comment by kghbln** [comment]
Since it was field tested by you I do not give a d... about the automated tests failing. I assume this will be rectified in consecutive pulls which potentially lead to new releases

**Comment by krabina** [comment]
I can confirm that it is working now, also the __NOGLOSSARY__
You should update the README thought, because you need to invoke Lingo in LocalSettings.php manually (right before Semantic Glossary) and upgrade to the latest version of Lingo...

**Comment by kghbln** [comment]
@krabina Thanks for the note. I will modify. About LIngo. We are talking about 3.1+ here?

**Comment by krabina** [comment]
yes I think so. I am on master, wich is 3.1.2 (257b1f7) 07:23, 28 June 2021, but it was working before as well (which probably was 3.1.1)

**Comment by kghbln** [comment]
Thanks for the info. I assume that 3.1 works here. Apart form that, there is no tagged version 3.1.2 but this does not surprise.

**Comment by kghbln** [comment]
@krabina Lucky you. Broken on https://sandbox.semantic-mediawiki.org/wiki/Glossary_test :(

**Comment by krabina** [comment]
Try the latest master of Lingo. And how can it be on PHP 7.2 when for MW 1.35 PHP 7.3 is required?

**Comment by kghbln** [comment]
This does not help either. I am on a MW 1.35 release candidate. PHP 7.3 was added later. Since I cannot upgrade the server I am stuck.

**Comment by kghbln** [comment]
I will test with another wiki once I get to it. I am not getting any fatals or errors in console. This alone is already a step forward.

**Pull request merged**
